config/routes.rb
Rails.application.routes.draw do

  resources :franchise_requests
  # mount Upmin::Engine => '/admin'
  root to: 'pages#index'
  get 'pages/schedule', to: 'pages#schedule'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      namespace :auth do
        resources :registrations, only: [:create] do
          collection do
            post :confirm
            post :resend_code
          end
        end
        resources :sessions, only: [:create] do
          collection do
            post :forgot

          end
        end
      end
      resources :lounges, only: [:index, :show]
      resources :reservations, only: [:index, :create, :destroy] do
        collection do
          get :load_data
        end
      end
      resources :tables, only: [:index]
      resources :skills, only: [:index] do
        member do
          post :take
          post :use
        end
      end
      resources :payments, only: [:create]
      resources :achievements, only: [:index] do
        member {
          post :viewed
        }
      end
      resources :search, only: [:index]
      resources :users, only: [:update, :show] do
        collection {
          get :rating
        }
        member {
          get :load_client_data
          get :load_hookmaster_data
        }
      end
      resources :works, only: [:index]
      resources :meets do
        member do
          post :accept
          post :decline
        end
      end
    end
  end
end

app/models/franchise_request.rb
class FranchiseRequest < ActiveRecord::Base
  validates :fio, presence: true

  after_create :send_inform

  def send_inform
    FranchiseMailer.new_request(self).deliver_now!
  end
end

app/controllers/franchise_requests_controller.rb
class FranchiseRequestsController < InheritedResources::Base
  skip_before_action :verify_authenticity_token
  respond_to :json
  private

    def franchise_request_params
      params.require(:franchise_request).permit(:fio, :contact_phone, :email, :city, :about, :employe_phone, :employe_status, :first_payment, :total_payment)
    end
end

app/helpers/franchise_requests_helper.rb
module FranchiseRequestsHelper
end

app/views/franchise_requests/_form.html.erb
<%= form_for(@franchise_request) do |f| %>
  <% if @franchise_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@franchise_request.errors.count, "error") %> prohibited this franchise_request from being saved:</h2>

      <ul>
      <% @franchise_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_field :about %>
  </div>
  <div class="field">
    <%= f.label :employe_phone %><br>
    <%= f.text_field :employe_phone %>
  </div>
  <div class="field">
    <%= f.label :employe_status %><br>
    <%= f.text_field :employe_status %>
  </div>
  <div class="field">
    <%= f.label :first_payment %><br>
    <%= f.text_field :first_payment %>
  </div>
  <div class="field">
    <%= f.label :total_payment %><br>
    <%= f.text_field :total_payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/franchise_requests/edit.html.erb
<h1>Editing Franchise Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @franchise_request %> |
<%= link_to 'Back', franchise_requests_path %>

app/views/franchise_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Franchise Requests</h1>

<table>
  <thead>
    <tr>
      <th>Fio</th>
      <th>Contact phone</th>
      <th>Email</th>
      <th>City</th>
      <th>About</th>
      <th>Employe phone</th>
      <th>Employe status</th>
      <th>First payment</th>
      <th>Total payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @franchise_requests.each do |franchise_request| %>
      <tr>
        <td><%= franchise_request.fio %></td>
        <td><%= franchise_request.contact_phone %></td>
        <td><%= franchise_request.email %></td>
        <td><%= franchise_request.city %></td>
        <td><%= franchise_request.about %></td>
        <td><%= franchise_request.employe_phone %></td>
        <td><%= franchise_request.employe_status %></td>
        <td><%= franchise_request.first_payment %></td>
        <td><%= franchise_request.total_payment %></td>
        <td><%= link_to 'Show', franchise_request %></td>
        <td><%= link_to 'Edit', edit_franchise_request_path(franchise_request) %></td>
        <td><%= link_to 'Destroy', franchise_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Franchise request', new_franchise_request_path %>

app/views/franchise_requests/new.html.erb
<h1>New Franchise Request</h1>

<%= render 'form' %>

<%= link_to 'Back', franchise_requests_path %>

app/views/franchise_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fio:</strong>
  <%= @franchise_request.fio %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @franchise_request.contact_phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @franchise_request.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @franchise_request.city %>
</p>

<p>
  <strong>About:</strong>
  <%= @franchise_request.about %>
</p>

<p>
  <strong>Employe phone:</strong>
  <%= @franchise_request.employe_phone %>
</p>

<p>
  <strong>Employe status:</strong>
  <%= @franchise_request.employe_status %>
</p>

<p>
  <strong>First payment:</strong>
  <%= @franchise_request.first_payment %>
</p>

<p>
  <strong>Total payment:</strong>
  <%= @franchise_request.total_payment %>
</p>

<%= link_to 'Edit', edit_franchise_request_path(@franchise_request) %> |
<%= link_to 'Back', franchise_requests_path %>